name: Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      
      - run: npm install -g pnpm
      - run: pnpm install
      - run: npx playwright install
      - run: pnpm test
