name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      OS: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['17']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Install dependencies 
        run: |
          npm install -g pnpm
          pnpm install
          npx playwright install

      - name: build
        run: pnpm turbo run build

      - name: Run tests 
        run: pnpm turbo run test
